# Generated by Django 3.1.5 on 2021-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type_of_project',
            field=models.CharField(choices=[('web', 'Website'), ('app', 'Mobile App'), ('ml', 'ML/DL')], default='web', max_length=30),
        ),
    ]
