# Generated by Django 3.1.5 on 2021-03-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project_type_of_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='icon_code',
            new_name='bx_icon_code',
        ),
    ]
