# Generated by Django 3.1.5 on 2021-10-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210302_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='members/')),
                ('description', models.TextField(null=True)),
                ('project_details', models.TextField(blank=True, null=True)),
                ('research_work', models.TextField(blank=True, null=True)),
                ('mail_id', models.CharField(max_length=200, null=True)),
                ('facebook', models.CharField(max_length=200, null=True)),
                ('linkedin', models.CharField(max_length=200, null=True)),
                ('whatsapp', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
