# Generated by Django 3.1.5 on 2021-10-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_viewmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viewmembers',
            name='image',
            field=models.ImageField(upload_to='viewmembers/'),
        ),
    ]
